### ISSUE TITLE
Question on Verifying Program Markers for Worse Optimization Cases in given C Code

### ISSUE THREAD

**Issue by H0w1** [DeadCodeProductions/program-markers#70]
Hello,

We are currently reproducing the work presented in your PLDI24 paper and would like some guidance. Specifically, we have some C code that relates to worse optimization cases as discussed in your paper. We are trying to determine if program markers can detect these worse optimization cases in our provided C code.

Could you help us find a straightforward way to achieve this?

**Comment by H0w1** [comment]
We have reviewed your PLDI artifact and noted that we can generate a new corpus using our C code files and then reuse your end-to-end tool. We examined the corpus generation process and found the following function in `root/cinstability/utils/generate_corpus.py`:
```
def generate(
    setting: CompilationSetting, number: int, jobs: int
) -> list[InstrumentedProgram]:
    programs = make_corpus(setting, number, jobs)
    iprograms = instrument_corpus(programs, jobs)
    while len(iprograms) < number:
        print(f"Only managed to generate {len(iprograms)}/{number} programs.")
        print("Generating more programs...")
        programs = make_corpus(setting, number - len(iprograms), jobs)
        iprograms.extend(instrument_corpus(programs, jobs))
    return iprograms
```

Our question is whether we can modify the line `programs = make_corpus(setting, number, jobs)` to something like `programs = get_corpus_from(src_path, number, jobs)`.

Do you have any suggestions for implementing this `get_corpus_from`, or is there a simpler approach we could take?

Thank you for your help!
Jianhao

**Comment by H0w1** [comment]
I implemented the above (building corpus from existing code to test compilers), but found that my code cases were not successfully instrumented. Was this normal?

Back to the beginning, my question may be unnecessary. According to my latest understanding, ProgramMarkers should be used to test whether the refined code is related to the compiler issues, not the original code.

**Comment by thetheodor** [comment]
Hi there, 

> I implemented the above (building corpus from existing code to test compilers), but found that my code cases were not successfully instrumented. Was this normal?

Can you share a snippet showing how you did this? 

One thing to note: the [instrumenter](https://github.com/DeadCodeProductions/program-markers/tree/main/src) has only been tested on code generated by Csmith and yarpgen, and thus it's likely to fail if the programs that you are testing if they are too "different" from the autogenerated ones. If this is the case, feel free to open another issue with a reduced example, I can have a look (and potentially fix the instrumenter).

> Back to the beginning, my question may be unnecessary. According to my latest understanding, ProgramMarkers should be used to test whether the refined code is related to the compiler issues, not the original code.

All the actual logic is implemented in this repository, the PLDI artifact simply wraps it in convenient scripts.

**Comment by H0w1** [comment]
Thank you for your response. I have some other questions about the ability of ProgramMarkers and dead.

Can I confirm that ProgramMarkers is designed to detect worse optimization in code that includes injected keywords such as `__builtin_unreachable()`? It appears that it cannot directly identify optimization issues that the compiler introduces in code that does not contain these keywords.

Regarding your other project, Dead, can I clarify that it detects cases where a compiler fails to optimize existing dead basic blocks in the source code? In other words, if a compiler introduces dead code during compilation, Dead is not able to see that.

**Comment by thetheodor** [comment]
Hi

> Can I confirm that ProgramMarkers is designed to detect worse optimization in code that includes injected keywords such as __builtin_unreachable()? It appears that it cannot directly identify optimization issues that the compiler introduces in code that does not contain these keywords.

The instrumenter in this repository can do the following:
- Insert DCEMarkers in the source code of a program wherever control flow diverges (as shown in the [README](https://github.com/DeadCodeProductions/program-markers))
- Insert VRMarkers roughly before each use of a variable (as shown in the [README](https://github.com/DeadCodeProductions/program-markers))

There's also[ a python wrapper ](https://github.com/DeadCodeProductions/program-markers/tree/main/python_src) (mostly undocumented), that uses the instrumenter and can perform the [differential](https://dl.acm.org/doi/10.1145/3503222.3507764) and [metamorphic](https://dl.acm.org/doi/10.1145/3656404) testing described in the two papers. Essentially given a (CSmith) program, it can insert markers, track which DCEMarkers are dead, track the ranges of VRMarkers, and also inject calls to the builtin unreachable wherever appropriate. The code in the artifact simply uses this python wrapper to drive the whole process.

This wrapper is not document but I could add some docs if that would be helpful/needed. A good starting point is the [test directory](https://github.com/DeadCodeProductions/program-markers/tree/main/python_src/test) that shows how the various pieces work together.

> Regarding your other project, Dead, can I clarify that it detects cases where a compiler fails to optimize existing dead basic blocks in the source code? In other words, if a compiler introduces dead code during compilation, Dead is not able to see that.

Yes, I don't believe that it can find dead code introduced by the compiler. Also that repository is a bit outdated, most of the functionality has been moved to `program-markers` and the [diopter](https://github.com/DeadCodeProductions/diopter) project.
